<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Title>LowDb Repositories</Title>
    <PackageId>LowDb.Net.Repositories</PackageId>
    <Description>A .NET implementation of the LowDB file-based database for use in applications and experiments that only require a minimal database implementation. Supports JSON-based database in web storage.
This extension provides the Repository pattern over a LowDb database.</Description>
    <PackageTags>LowDb; file-based database; data files; repository</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\package-icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="D20Tek.Functional" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\D20Tek.LowDb\D20Tek.LowDb.csproj" />
  </ItemGroup>

</Project>
