<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>LowDb.Net.Browser</PackageId>
    <Title>LowDb for .Net (Browser Extensions)</Title>
    <Description>A .NET implementation of the LowDB file-based database for use in applications and experiments that only require a minimal database implementation. Supports JSON-based database in web storage.</Description>
    <PackageTags>LowDb; file-based database; data files</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="D20Tek.Blazor.BrowserStorage" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\D20Tek.LowDb\D20Tek.LowDb.csproj" />
  </ItemGroup>

</Project>
